# Experiment
# new task network
exp_id: clf_3_featcat_10k_wt_6
output_dir: &output ../outputs
train_model: True
test_model: True

# Data
data:
    path_load: ../data/data_tadpole_3.pickle
    path_meta: ../data/metadata
    path_images: ../../../ADNI_data/data
    path_feat: ../data/features.csv
    min_visits: 2

datagen:
    data_split: &data_split 0.8
    batch_size: &bsize 128
    num_visits: &T 0
    feat_flag: &imgType tadpole 

# Model 
model:
    load_model: '' #../outputs/clf_3_ipcat_5k_wt_6/checkpoints/model.pth
    num_classes: &numcls 3
    class_wt: [1., 1.3, 2]
    module_image:
        name: tadpole2
        num_input: 692
        num_output: 500
    module_temporal: 
        name: rnn
        num_input: 520
        num_timesteps: *T 
    module_forecast:
        name: append_time
    module_task:
        name: dx1
        num_input: 520
        num_classes: *numcls
    fusion: concat_feature

# Train 
train:
    num_epochs: 10000
    save_model: True

# Test
test:
    task: classify
    data_split: *data_split
    batch_size: *bsize
    feat_flag: *imgType

