# Experiment
exp_id: debug_test
output_dir: &output ../outputs
train_model: False 
test_model: True    

# Data
data:
    path_load: ../data/data.pickle
    path_feat: ../data/TADPOLE_D1_D2.csv
    min_visits: 2

datagen:
    data_split: &data_split 0.8
    batch_size: &bsize 32
    num_visits: &T 3
    feat_flag: &imgType tadpole 

# Model 
model:
    load_model: '../outputs/forecast_3_featcat_proposed_20k_4_3/checkpoints/model.pth'
    class_wt: [1, 1.3, 2]
    module_image:
        name: tadpole
        num_input: 692
        num_output: 1000
    module_temporal: 
        name: forecastRNN
        num_input: 520
        num_timesteps: *T 
    module_forecast:
        name: append_time
    module_task:
        name: dx
        num_input: 520
        num_classes: 3 
    fusion: concat_feature

# Train 
train:
    num_epochs: 10
    log_period: 3
    ckpt_period: 3
    save_model: True

# Test
test:
    batch_size: *bsize
    feat_flag: *imgType

