# Experiment
exp_id: exp1
output_dir: &output ../outputs
train_model: True
test_model: False  

# Data
data:
    path_load: ../data/data_new.pickle
    path: ../data/TADPOLE_D1_D2_proc.csv
    min_visits: 2
    only_consecutive: True

datagen:
    data_split: &data_split 0.8
    batch_size: &bsize 8
    max_visits: &T 6 

# Model 
model:
    load_model: '' # '../outputs/flare_pretrained/checkpoints/model.pth'
    class_wt: [1, 1.3, 2]
    module_image:
        name: tadpole
        num_input: 656
        num_output: 1000
    module_temporal: 
        name: forecastRNN
        num_input: 520
        num_timesteps: *T 
    module_forecast:
        name: append_time
    module_task:
        name: dx
        num_input: 520
        num_classes: 3 
    fusion: concat_feature

# Train 
train:
    num_epochs: 5
    log_period: 1
    ckpt_period: 1
    validation_period: 1
    save_model: True

# Test
test:
    batch_size: *bsize
    # feat_flag: *imgType

