# Experiment
exp_id: forecast_iter_debug_loss_spike_exp3_no_bn_T4
output_dir: &output ../outputs
train_model: True
test_model: True

# Data
data:
    path_load: ../data/data_norm_all_1.pickle
    path: ../data/TADPOLE_D1_D2_proc_norm_all_1.csv
    train_ids_path: ../data/patientID_train_all.txt
    test_ids_path: ../data/patientID_test_all.txt
    min_visits: 2
    only_consecutive: True
    data_split: &data_split 0.8

datagen:
    batch_size: &bsize 16
    max_visits: &T 4
    max_T : 4

# Model 
model:
    load_model: '' #'/mnt/nfs/work1/mfiterau/yeahuaywu/flare/outputs/forecast_iter_debug_loss_spike_exp2/forecast_iter_debug_loss_spike_exp2_4/checkpoints/model_ep28.pth' #../outputs/forecast_6_6/checkpoints/model_ep20.pth'

    # class_wt: [1.36, 1, 1.78] # [1, 1.3, 2]
    module_image:
        name: tadpole_no_bn
        num_input: 656
        num_output: 1000
    module_temporal: 
        name: forecastRNN
        num_input: 520
        num_timesteps: *T 
    module_forecast:
        name: append_time
    module_task:
        name: dx
        num_input: 520
        num_classes: 3 
    fusion: concat_feature

# Train 
train:
    num_epochs: 30
    log_period: 1
    ckpt_period: 30
    validation_period: 1
    save_model: True
    num_iter: 5

