exp_id: T4_rand_debug
output_dir: &output ../outputs/skorch-debug

#Data
data:
    path_load: ../data/data_norm_test.pickle
    path: ../data/TADPOLE_D1_D2_proc_norm_test.csv
    train_ids_path: ../data/patientID_train.txt
    test_ids_path: ../data/patientID_test.txt
    min_visits: 2
    only_consecutive: True
    data_split: &data_split 0.8

datagen:
    batch_size: &bsize 32
    max_visits: &T 5
    max_T : 5
    dataload_method: None

# Model 
model:
    module__image:
        name: tadpole
        params:
            num_input: 656
            num_output: 1000
    module__temporal: 
        name: forecastRNN
        params:
            num_input: 520
            num_timesteps: *T 
    module__forecast:
        name: append_time
    module__task:
        name: dx
        params:
            num_input: 520
            num_classes: 3 
    module__fusion: concat_feature
    module__aux_loss: MSE
    module__aux_loss_scale: 10000
    iterator_train__drop_last: True
    iterator_valid__drop_last: True

