output_dir: &output ../outputs/skorch-debug/7.18.2019

#Data
data:
    path_load: ../data/data_norm_test.pickle
    path: ../data/TADPOLE_D1_D2_proc_norm_test.csv
    train_ids_path: ../data/patientID_train.txt
    test_ids_path: ../data/patientID_test.txt
    min_visits: 2
    only_consecutive: True
    data_split: &data_split 0.8

datagen:
    max_visits: &T 5
    max_T : 5
    batch_size: 32
    dataload_method: None

# Model 
model:
    module__image:
        name: covtest
        params:
            num_input: 7
            num_output: 7
    module__temporal: 
        name: forecastRNN_covtest
        params:
            num_input: 7
            num_timesteps: *T 
    module__forecast:
        name: append_time
    module__task:
        name: dx2
        params:
            num_input: 7
            num_classes: 3 
    module__fusion: concat_input
    module__aux_loss: MSE
    module__aux_loss_scale: 1000
    iterator_train__drop_last: True
    iterator_valid__drop_last: True

