# Experiment
exp_id: debug_MSE
output_dir: &output ../outputs/7.10.2019-2/flare
train_model: True
test_model: True
num_iter: 2

# Data
data:
    path_load: ../data/data_norm_subsetT4.pickle
    path: ../data/TADPOLE_D1_D2_proc_norm_test.csv
    train_ids_path: ../data/patientID_train.txt
    test_ids_path: ../data/patientID_test.txt
    min_visits: 2
    only_consecutive: True
    data_split: &data_split 0.8

datagen:
    batch_size: &bsize 32
    max_visits: &T 5
    max_T : 5
    dataload_method: uniform

# Model 
model:
    load_model: '' #'/mnt/nfs/work1/mfiterau/yeahuaywu/flare/outputs/forecast_iter_debug_loss_spike_exp2/forecast_iter_debug_loss_spike_exp2_4/checkpoints/model_ep28.pth' #../outputs/forecast_6_6/checkpoints/model_ep20.pth'
    # class_wt: [1.36, 1, 1.78] # [1, 1.3, 2]
    early_stopping: True
    learning_rate: .0019
    weight_decay: .001
    init:
        rnn_init: True
        linear_init: True
    module_image:
        name: tadpole
        num_input: 656
        num_output: 1000
    module_temporal: 
        name: forecastRNN
        num_input: 520
        num_timesteps: *T 
    module_forecast:
        name: append_time
    module_task:
        name: dx
        num_input: 520
        num_classes: 3 
    fusion: concat_feature
    aux_loss: MSE
    aux_loss_scale: 8000
