# Experiment
exp_id: flare-cov
output_dir: &output ../outputs/11.13.2020/flare
train_model: True
test_model: True
num_iter: 5

# Data
data:
    path_load: ../data/tadpole_data.pkl
    path: ../data/TADPOLE_D1_D2_proc_norm_test.csv
    train_ids_path: ../data/patientID_train.txt
    test_ids_path: ../data/patientID_test.txt
    min_visits: 2
    only_consecutive: True
    data_split: &data_split 0.8

datagen:
    batch_size: &bsize 128
    max_visits: &T 5
    max_T : 5
    dataload_method: None

# Model
model:
    load_model: '' #'/mnt/nfs/work1/mfiterau/yeahuaywu/flare/outputs/forecast_iter_debug_loss_spike_exp2/forecast_iter_debug_loss_spike_exp2_4/checkpoints/model_ep28.pth' #../outputs/forecast_6_6/checkpoints/model_ep20.pth'
    # class_wt: [1.36, 1, 1.78] # [1, 1.3, 2]
    early_stopping: True
    learning_rate: .001
    weight_decay: 0.00333
    init:
        rnn_init: True
        linear_init: True
    module_image:
        name: covtest
        num_input: 7
        num_output: 7
    module_temporal:
        name: forecastRNN_covtest
        num_input: 7
        num_timesteps: *T
    module_forecast:
        name: append_time
    module_task:
        name: dx2
        num_input: 7
        num_classes: 3
    module_concat:
      name: null
      val: False
    fusion: concat_input
    aux_loss: MSE
    aux_loss_scale: 1000

# Train
train:
    num_epochs: 60
    log_period: 1
    ckpt_period: 1
    validation_period: 1
    save_model: True


